version: '3'

services:
  odoo:
    image: odoo:16
    depends_on:
      - db
      - redis
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo_password
    ports:
      - "8070:8069"
    volumes:
      - ./odoo:/mnt/extra-addons

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo_password
    volumes:
      - odoo-db-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6380:6379"

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - odoo
      - redis
    environment:
      - BROKER_URL=redis://redis:6379/0
    volumes:
      - ./odoo:/mnt/extra-addons
    command: celery -A odoo_module worker --loglevel=info

volumes:
  odoo-db-data:
